function style_a1(lbl_title,lbl_measureUnit,lbl_digitValue,lbl_gaugeCoef,itm_labels) {
    lbl_title.verticalAlignment     = Text.AlignVCenter
    lbl_title.horizontalAlignment   = Text.AlignHCenter
    lbl_title.border.width          = 1
    lbl_title.border.color          = "#e34c22"
    lbl_title.anchors.horizontalCenter  = itm_labels.horizontalCenter
    lbl_title.anchors.verticalCenter    = itm_labels.verticalCenter
    lbl_title.anchors.horizontalCenterOffset    = 0
    lbl_title.anchors.verticalCenterOffset      = -80
    lbl_title.font.family           = "Times New Roman"
    lbl_title.font.pixelSize        = 13
    lbl_title.color                 = "transparent"
    lbl_title.textColor             = "white"
    lbl_title.width                 = 115
    lbl_title.height                = 25
    lbl_title.radius                = 5

    lbl_measureUnit.verticalAlignment   = Text.AlignVCenter
    lbl_measureUnit.horizontalAlignment = Text.AlignHCenter
    lbl_measureUnit.border.width        = 0
    lbl_measureUnit.border.color        = "#e34c22"
    lbl_measureUnit.anchors.horizontalCenter        = itm_labels.horizontalCenter
    lbl_measureUnit.anchors.verticalCenter          = itm_labels.verticalCenter
    lbl_measureUnit.anchors.horizontalCenterOffset  = 0
    lbl_measureUnit.anchors.verticalCenterOffset    = -50
    lbl_measureUnit.font.family     = "Times New Roman"
    lbl_measureUnit.font.pixelSize  = 13
    lbl_measureUnit.color       = "transparent"
    lbl_measureUnit.textColor   = "white"
    lbl_measureUnit.width       = 100
    lbl_measureUnit.height      = 25
    lbl_measureUnit.radius      = 5

    lbl_digitValue.verticalAlignment        = Text.AlignVCenter
    lbl_digitValue.horizontalAlignment      = Text.AlignHCenter
    lbl_digitValue.anchors.horizontalCenter = itm_labels.horizontalCenter
    lbl_digitValue.anchors.verticalCenter   = itm_labels.verticalCenter
    lbl_digitValue.anchors.horizontalCenterOffset   = 0
    lbl_digitValue.anchors.verticalCenterOffset     = 0
    lbl_digitValue.font.family      = "Times New Roman"
    lbl_digitValue.font.pixelSize   = 13
    lbl_digitValue.color            = "white"
    lbl_digitValue.textColor        = "#e34c22"
    lbl_digitValue.width            = 50
    lbl_digitValue.height           = 50
    lbl_digitValue.visible          = true
    lbl_digitValue.radius           = 25
    lbl_digitValue.border.width     = 2
    lbl_digitValue.border.color     = "#e34c22"

    lbl_gaugeCoef.verticalAlignment     = Text.AlignVCenter
    lbl_gaugeCoef.horizontalAlignment   = Text.AlignHCenter
    lbl_gaugeCoef.border.width          = 0
    lbl_gaugeCoef.border.color          = "#e34c22"
    lbl_gaugeCoef.anchors.horizontalCenter      = itm_labels.horizontalCenter
    lbl_gaugeCoef.anchors.verticalCenter        = itm_labels.verticalCenter
    lbl_gaugeCoef.anchors.horizontalCenterOffset= 0
    lbl_gaugeCoef.anchors.verticalCenterOffset  = 50
    lbl_gaugeCoef.font.family   = "Times New Roman"
    lbl_gaugeCoef.font.pixelSize= 13
    lbl_gaugeCoef.color         = "transparent"
    lbl_gaugeCoef.textColor     = "white"
    lbl_gaugeCoef.width         = 115
    lbl_gaugeCoef.height        = 25
    lbl_gaugeCoef.radius        = 5
}

function style_a5(lbl_title,lbl_measureUnit,lbl_digitValue,lbl_gaugeCoef,itm_labels) {
    lbl_title.verticalAlignment     = Text.AlignVCenter
    lbl_title.horizontalAlignment   = Text.AlignHCenter
    lbl_title.border.width          = 1
    lbl_title.border.color          = "#e34c22"
    lbl_title.anchors.horizontalCenter  = itm_labels.horizontalCenter
    lbl_title.anchors.verticalCenter    = itm_labels.verticalCenter
    lbl_title.anchors.horizontalCenterOffset    = 0
    lbl_title.anchors.verticalCenterOffset      = -80
    lbl_title.font.family           = "Times New Roman"
    lbl_title.font.pixelSize        = 13
    lbl_title.color                 = "transparent"
    lbl_title.textColor             = "white"
    lbl_title.width                 = 115
    lbl_title.height                = 25
    lbl_title.radius                = 5

    lbl_measureUnit.verticalAlignment   = Text.AlignVCenter
    lbl_measureUnit.horizontalAlignment = Text.AlignHCenter
    lbl_measureUnit.border.width        = 0
    lbl_measureUnit.border.color        = "#e34c22"
    lbl_measureUnit.anchors.horizontalCenter        = itm_labels.horizontalCenter
    lbl_measureUnit.anchors.verticalCenter          = itm_labels.verticalCenter
    lbl_measureUnit.anchors.horizontalCenterOffset  = 30
    lbl_measureUnit.anchors.verticalCenterOffset    = 50
    lbl_measureUnit.font.family     = "Times New Roman"
    lbl_measureUnit.font.pixelSize  = 13
    lbl_measureUnit.color       = "transparent"
    lbl_measureUnit.textColor   = "white"
    lbl_measureUnit.width       = 100
    lbl_measureUnit.height      = 25
    lbl_measureUnit.radius      = 5

    lbl_digitValue.verticalAlignment        = Text.AlignVCenter
    lbl_digitValue.horizontalAlignment      = Text.AlignHCenter
    lbl_digitValue.anchors.horizontalCenter = itm_labels.horizontalCenter
    lbl_digitValue.anchors.verticalCenter   = itm_labels.verticalCenter
    lbl_digitValue.anchors.horizontalCenterOffset   = -30
    lbl_digitValue.anchors.verticalCenterOffset     = 50
    lbl_digitValue.font.family      = "Times New Roman"
    lbl_digitValue.font.pixelSize   = 16
    lbl_digitValue.font.bold        = true
    lbl_digitValue.color            = "black"
    lbl_digitValue.textColor        = "white"
    lbl_digitValue.width            = 60
    lbl_digitValue.height           = 30
    lbl_digitValue.visible          = true
    lbl_digitValue.radius           = 2
    lbl_digitValue.border.width     = 1
    lbl_digitValue.border.color     = "#e34c22"

    lbl_gaugeCoef.verticalAlignment     = Text.AlignVCenter
    lbl_gaugeCoef.horizontalAlignment   = Text.AlignHCenter
    lbl_gaugeCoef.border.width          = 0
    lbl_gaugeCoef.border.color          = "#e34c22"
    lbl_gaugeCoef.anchors.horizontalCenter      = itm_labels.horizontalCenter
    lbl_gaugeCoef.anchors.verticalCenter        = itm_labels.verticalCenter
    lbl_gaugeCoef.anchors.horizontalCenterOffset= 0
    lbl_gaugeCoef.anchors.verticalCenterOffset  = -40
    lbl_gaugeCoef.font.family   = "Times New Roman"
    lbl_gaugeCoef.font.pixelSize= 13
    lbl_gaugeCoef.color         = "transparent"
    lbl_gaugeCoef.textColor     = "white"
    lbl_gaugeCoef.width         = 115
    lbl_gaugeCoef.height        = 25
    lbl_gaugeCoef.radius        = 5
}

function style_a6(lbl_title,lbl_measureUnit,lbl_digitValue,lbl_gaugeCoef,itm_labels) {
    lbl_title.verticalAlignment     = Text.AlignVCenter
    lbl_title.horizontalAlignment   = Text.AlignHCenter
    lbl_title.border.width          = 1
    lbl_title.border.color          = "#e34c22"
    lbl_title.anchors.horizontalCenter  = itm_labels.horizontalCenter
    lbl_title.anchors.verticalCenter    = itm_labels.verticalCenter
    lbl_title.anchors.horizontalCenterOffset    = 0
    lbl_title.anchors.verticalCenterOffset      = -80
    lbl_title.font.family           = "Times New Roman"
    lbl_title.font.pixelSize        = 13
    lbl_title.color                 = "transparent"
    lbl_title.textColor             = "white"
    lbl_title.width                 = 115
    lbl_title.height                = 25
    lbl_title.radius                = 5

    lbl_measureUnit.verticalAlignment   = Text.AlignVCenter
    lbl_measureUnit.horizontalAlignment = Text.AlignHCenter
    lbl_measureUnit.border.width        = 0
    lbl_measureUnit.border.color        = "#e34c22"
    lbl_measureUnit.anchors.horizontalCenter        = itm_labels.horizontalCenter
    lbl_measureUnit.anchors.verticalCenter          = itm_labels.verticalCenter
    lbl_measureUnit.anchors.horizontalCenterOffset  = 0
    lbl_measureUnit.anchors.verticalCenterOffset    = 50
    lbl_measureUnit.font.family     = "Times New Roman"
    lbl_measureUnit.font.pixelSize  = 13
    lbl_measureUnit.color       = "transparent"
    lbl_measureUnit.textColor   = "white"
    lbl_measureUnit.width       = 100
    lbl_measureUnit.height      = 25
    lbl_measureUnit.radius      = 5

    lbl_digitValue.verticalAlignment        = Text.AlignVCenter
    lbl_digitValue.horizontalAlignment      = Text.AlignHCenter
    lbl_digitValue.anchors.horizontalCenter = itm_labels.horizontalCenter
    lbl_digitValue.anchors.verticalCenter   = itm_labels.verticalCenter
    lbl_digitValue.anchors.horizontalCenterOffset   = 0
    lbl_digitValue.anchors.verticalCenterOffset     = -40
    lbl_digitValue.font.family      = "Times New Roman"
    lbl_digitValue.font.pixelSize   = 16
    lbl_digitValue.font.bold        = true
    lbl_digitValue.color            = "black"
    lbl_digitValue.textColor        = "white"
    lbl_digitValue.width            = 60
    lbl_digitValue.height           = 30
    lbl_digitValue.visible          = true
    lbl_digitValue.radius           = 2
    lbl_digitValue.border.width     = 1
    lbl_digitValue.border.color     = "#e34c22"

    lbl_gaugeCoef.verticalAlignment     = Text.AlignVCenter
    lbl_gaugeCoef.horizontalAlignment   = Text.AlignHCenter
    lbl_gaugeCoef.border.width          = 0
    lbl_gaugeCoef.border.color          = "#e34c22"
    lbl_gaugeCoef.anchors.horizontalCenter      = itm_labels.horizontalCenter
    lbl_gaugeCoef.anchors.verticalCenter        = itm_labels.verticalCenter
    lbl_gaugeCoef.anchors.horizontalCenterOffset= 0
    lbl_gaugeCoef.anchors.verticalCenterOffset  = 30
    lbl_gaugeCoef.font.family   = "Times New Roman"
    lbl_gaugeCoef.font.pixelSize= 13
    lbl_gaugeCoef.color         = "transparent"
    lbl_gaugeCoef.textColor     = "white"
    lbl_gaugeCoef.width         = 115
    lbl_gaugeCoef.height        = 25
    lbl_gaugeCoef.radius        = 5
}

function style_a2(lbl_title,lbl_measureUnit,lbl_digitValue,lbl_gaugeCoef,itm_labels) {
    lbl_title.verticalAlignment     = Text.AlignVCenter
    lbl_title.horizontalAlignment   = Text.AlignHCenter
    lbl_title.border.width          = 1
    lbl_title.border.color          = "#e34c22"
    lbl_title.anchors.horizontalCenter  = itm_labels.horizontalCenter
    lbl_title.anchors.verticalCenter    = itm_labels.verticalCenter
    lbl_title.anchors.horizontalCenterOffset    = 0
    lbl_title.anchors.verticalCenterOffset      = -45
    lbl_title.font.family           = "Times New Roman"
    lbl_title.font.pixelSize        = 13
    lbl_title.color                 = "transparent"
    lbl_title.textColor             = "white"
    lbl_title.width                 = 115
    lbl_title.height                = 25
    lbl_title.radius                = 5

    lbl_measureUnit.verticalAlignment   = Text.AlignVCenter
    lbl_measureUnit.horizontalAlignment = Text.AlignHCenter
    lbl_measureUnit.border.width        = 0
    lbl_measureUnit.border.color        = "#e34c22"
    lbl_measureUnit.anchors.horizontalCenter        = itm_labels.horizontalCenter
    lbl_measureUnit.anchors.verticalCenter          = itm_labels.verticalCenter
    lbl_measureUnit.anchors.horizontalCenterOffset  = 60
    lbl_measureUnit.anchors.verticalCenterOffset    = 0
    lbl_measureUnit.font.family     = "Times New Roman"
    lbl_measureUnit.font.pixelSize  = 15
    lbl_measureUnit.font.bold       = true
    lbl_measureUnit.color       = "transparent"
    lbl_measureUnit.textColor   = "white"
    lbl_measureUnit.width       = 100
    lbl_measureUnit.height      = 25
    lbl_measureUnit.radius      = 5

    lbl_digitValue.verticalAlignment        = Text.AlignVCenter
    lbl_digitValue.horizontalAlignment      = Text.AlignHCenter
    lbl_digitValue.anchors.horizontalCenter = itm_labels.horizontalCenter
    lbl_digitValue.anchors.verticalCenter   = itm_labels.verticalCenter
    lbl_digitValue.anchors.horizontalCenterOffset   = 0
    lbl_digitValue.anchors.verticalCenterOffset     = 0
    lbl_digitValue.width            = 50
    lbl_digitValue.height           = 50
    lbl_digitValue.visible          = true
    lbl_digitValue.radius           = 25
    lbl_digitValue.border.width     = 2
    lbl_digitValue.border.color     = "#e34c22"
    lbl_digitValue.color            = "transparent";
    lbl_digitValue.textColor        = "white"
    lbl_digitValue.font.family      =  "Times New Roman"
    lbl_digitValue.font.pixelSize   = 13
    lbl_digitValue.font.bold        = true

    lbl_gaugeCoef.verticalAlignment     = Text.AlignVCenter
    lbl_gaugeCoef.horizontalAlignment   = Text.AlignHCenter
    lbl_gaugeCoef.border.width          = 0
    lbl_gaugeCoef.border.color          = "#e34c22"
    lbl_gaugeCoef.anchors.horizontalCenter      = itm_labels.horizontalCenter
    lbl_gaugeCoef.anchors.verticalCenter        = itm_labels.verticalCenter
    lbl_gaugeCoef.anchors.horizontalCenterOffset= 0
    lbl_gaugeCoef.anchors.verticalCenterOffset  = 50
    lbl_gaugeCoef.font.family   = "Times New Roman"
    lbl_gaugeCoef.font.pixelSize= 13
    lbl_gaugeCoef.color         = "transparent"
    lbl_gaugeCoef.textColor     = "white"
    lbl_gaugeCoef.width         = 115
    lbl_gaugeCoef.height        = 25
    lbl_gaugeCoef.radius        = 5
}

function style_a3(lbl_title,lbl_measureUnit,lbl_digitValue,lbl_gaugeCoef,itm_labels) {
    lbl_digitValue.font.family      =  "Times New Roman"
    lbl_digitValue.font.pixelSize   = 13
    lbl_digitValue.color            = "transparent";
    lbl_digitValue.textColor        = "white"
    lbl_digitValue.radius   = 0;
    lbl_digitValue.anchors.bottom               = itm_labels.bottom
    lbl_digitValue.anchors.bottomMargin         = -56
    lbl_digitValue.width        = 56
    lbl_digitValue.height       = 56
    lbl_digitValue.verticalAlignment        = Text.AlignVCenter
    lbl_digitValue.horizontalAlignment      = Text.AlignHCenter
    lbl_digitValue.anchors.horizontalCenter = itm_labels.horizontalCenter
    lbl_digitValue.anchors.horizontalCenterOffset   = 0
    lbl_digitValue.anchors.verticalCenterOffset     = 0
    lbl_digitValue.border.width     = 2
    lbl_digitValue.border.color     = "#e34c22"

    lbl_measureUnit.verticalAlignment   = Text.AlignVCenter
    lbl_measureUnit.horizontalAlignment = Text.AlignHCenter
    lbl_measureUnit.border.width        = 0
    lbl_measureUnit.border.color        = "#e34c22"
    lbl_measureUnit.anchors.horizontalCenter        = itm_labels.horizontalCenter
    lbl_measureUnit.color       = "transparent"
    lbl_measureUnit.textColor   = "white"
    lbl_measureUnit.width       = 100
    lbl_measureUnit.height      = 25
    lbl_measureUnit.radius      = 5
    lbl_measureUnit.font.family = "Times New Roman"
    lbl_measureUnit.font.pixelSize  = 11
    lbl_measureUnit.anchors.bottom              = itm_labels.bottom
    lbl_measureUnit.anchors.bottomMargin        = -55
    lbl_measureUnit.anchors.horizontalCenterOffset  = 0

    lbl_title.anchors.top       = itm_labels.top
    lbl_title.anchors.topMargin = -30
    lbl_title.border.width      = 0
    lbl_title.verticalAlignment     = Text.AlignVCenter
    lbl_title.horizontalAlignment   = Text.AlignHCenter
    lbl_title.anchors.horizontalCenter  = itm_labels.horizontalCenter
    lbl_title.anchors.horizontalCenterOffset    = 0
    lbl_title.font.family           = "Times New Roman"
    lbl_title.font.pixelSize        = 13
    lbl_title.color                 = "transparent"
    lbl_title.textColor             = "white"
    lbl_title.width                 = 115
    lbl_title.height                = 25
    lbl_title.radius                = 5

    lbl_gaugeCoef.verticalAlignment     = Text.AlignVCenter
    lbl_gaugeCoef.horizontalAlignment   = Text.AlignHCenter
    lbl_gaugeCoef.border.width          = 0
    lbl_gaugeCoef.border.color          = "#e34c22"
    lbl_gaugeCoef.anchors.horizontalCenter      = itm_labels.horizontalCenter
    lbl_gaugeCoef.anchors.verticalCenter        = itm_labels.verticalCenter
    lbl_gaugeCoef.anchors.horizontalCenterOffset= 0
    lbl_gaugeCoef.anchors.verticalCenterOffset  = 50
    lbl_gaugeCoef.font.family   = "Times New Roman"
    lbl_gaugeCoef.font.pixelSize= 13
    lbl_gaugeCoef.color         = "transparent"
    lbl_gaugeCoef.textColor     = "white"
    lbl_gaugeCoef.width         = 115
    lbl_gaugeCoef.height        = 25
    lbl_gaugeCoef.radius        = 5
    lbl_gaugeCoef.visible       = false
}

function style_a4(lbl_title,lbl_measureUnit,lbl_digitValue,lbl_gaugeCoef,itm_labels) {
//    style_a2(lbl_title,lbl_measureUnit,lbl_digitValue,lbl_gaugeCoef,itm_labels)

    lbl_digitValue.verticalAlignment        = Text.AlignVCenter
    lbl_digitValue.horizontalAlignment      = Text.AlignHCenter
    lbl_digitValue.anchors.verticalCenterOffset     = 0
    lbl_digitValue.visible          = true
    lbl_digitValue.border.width     = 2
    lbl_digitValue.border.color     = "#e34c22"
    lbl_digitValue.color            = "transparent";
    lbl_digitValue.textColor        = "white"
    lbl_digitValue.font.family      =  "Times New Roman"
    lbl_digitValue.font.pixelSize   = 13
    lbl_digitValue.font.bold        = true
    lbl_digitValue.radius   = 0
    lbl_digitValue.anchors.right        = itm_labels.right
    lbl_digitValue.anchors.rightMargin  = -56
    lbl_digitValue.width                = 56
    lbl_digitValue.height               = 56

    lbl_measureUnit.border.width        = 0
    lbl_measureUnit.border.color        = "#e34c22"
    lbl_measureUnit.color       = "transparent"
    lbl_measureUnit.textColor   = "white"
    lbl_measureUnit.height      = 25
    lbl_measureUnit.radius      = 5
    lbl_measureUnit.width               = 55;
    lbl_measureUnit.font.family         = "Times New Roman"
    lbl_measureUnit.font.pixelSize      = 11
    lbl_measureUnit.anchors.bottom              = itm_labels.bottom
    lbl_measureUnit.anchors.bottomMargin        = 4
    lbl_measureUnit.anchors.right               = itm_labels.right
    lbl_measureUnit.anchors.rightMargin         = -56;
    lbl_measureUnit.horizontalAlignment         = Text.AlignHCenter;
    lbl_measureUnit.verticalAlignment           = Text.AlignBottom;

    lbl_title.verticalAlignment     = Text.AlignVCenter
    lbl_title.horizontalAlignment   = Text.AlignHCenter
    lbl_title.anchors.horizontalCenter  = itm_labels.horizontalCenter
    lbl_title.anchors.horizontalCenterOffset    = 0
    lbl_title.anchors.top                       = itm_labels.top
    lbl_title.anchors.topMargin                 = -60;
    lbl_title.border.width                      = 0;
    lbl_title.font.family           = "Times New Roman"
    lbl_title.font.pixelSize        = 13
    lbl_title.color                 = "transparent"
    lbl_title.textColor             = "white"
    lbl_title.width                 = 115
    lbl_title.height                = 25
    lbl_title.radius                = 5

    lbl_gaugeCoef.verticalAlignment     = Text.AlignVCenter
    lbl_gaugeCoef.horizontalAlignment   = Text.AlignHCenter
    lbl_gaugeCoef.border.width          = 0
    lbl_gaugeCoef.border.color          = "#e34c22"
    lbl_gaugeCoef.anchors.horizontalCenter      = itm_labels.horizontalCenter
    lbl_gaugeCoef.anchors.verticalCenter        = itm_labels.verticalCenter
    lbl_gaugeCoef.anchors.horizontalCenterOffset= 0
    lbl_gaugeCoef.anchors.verticalCenterOffset  = 50
    lbl_gaugeCoef.font.family   = "Times New Roman"
    lbl_gaugeCoef.font.pixelSize= 13
    lbl_gaugeCoef.color         = "transparent"
    lbl_gaugeCoef.textColor     = "white"
    lbl_gaugeCoef.width         = 115
    lbl_gaugeCoef.height        = 25
    lbl_gaugeCoef.radius        = 5
    lbl_gaugeCoef.visible       = false
}
